###服务启动端口号
server:
  port: 8000
###服务名称(服务注册到eureka名称)  
spring:
    application:
        name: Eureka-provider
###服务注册到eureka地址
eureka:
  client:
    service-url:
           defaultZone: http://localhost:8100/eureka,http://localhost:8200/eureka

           
###因为该应用为注册中心，不会注册自己
    register-with-eureka: true
###是否需要从eureka上获取注册信息
    fetch-registry: true
    
###心跳时间与持续时间配置
###本地测试时将值设小些，保证服务关闭时注册中心能及时剔除
  instance:
    ####EurekaClient向EurekaServer发送心跳包间隔时间 （单位：s）
    lease-renewal-interval-in-seconds: 1
    ###EurekaServer收到最后一次心跳包的等待时间上限（单位：s）
    lease-expiration-duration-in-seconds: 2
    
    

