###服务启动端口号
server:
  port: 8801
###服务名称(服务注册到Zookeeper名称)  
spring:
    application:
        name: Zookeeper-consumer
###服务注册到Zookeeper地址    cloud:
      zookeeper:
        connect-string: 127.0.0.1:2181     

           

