###服务端口号
server:
  port: 8100
  
###eureka 基本信息配置
spring: 
 application: 
  name: eureka-server
  
eureka:
  instance:
    ###注册到eurekaip地址
    hostname: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8200/eureka/
###因为自己是为注册中心，不需要自己注册自己
    register-with-eureka: true
###因为自己是为注册中心，不需要检索服务
    fetch-registry: true
  
  server:
   ###本地开发关闭 Eureka 自我保护机制 
   enable-self-preservation: false
   eviction-interval-timer-in-ms: 2000

    
        

    